name: 'A Discord Webhook Action'
description: 'Send discord webhook message'
inputs:
  webhook-url:
    description: 'Discord webhook url'
    required: true
  type:
    description: "A type of webhook"
    required: true
  content:
    description: "A message to send"
    required: false
  username:
    description: "A username to send"
    required: false
  title:
    description: "A title to send"
    required: false
  description:
    description: "A description to send"
    required: false
  url:
    description: "A url to send"
    required: false

outputs:
  result:
    description: 'Success to send webhook message'
    
runs:
  using: 'node20'
  main: 'dist/index.js'
